spring:
  application:
    name: tcom-admin-api
  profiles:
    active: dev
  mvc:
    path-match:
      matching-strategy: ant_path_matcher #??
  servlet:
    multipart:
      max-file-size: 10MB #???????????10M
      max-request-size: 100MB  #???????????10M


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://121.43.185.118:3306/medicine_online?useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root_wrj
      password: wangruijiang123W@

      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000

  data:
    redis:
      host: 127.0.0.1
      password:
      port: 6379

  spring:
    security:
      user:
        name: admin        # 设置开发环境用户名
        password: 47e5a4e6-2955-40d0-9e95-3ddabfbc8c67 # 设置开发环境密码
        roles:  ADMIN  # 设置角色（可选）


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: top.zhu.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  plugins:
      - com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor
      - com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor

  global-config:
    db-config:
      logic-delete-field: true # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)

server:
  port: 8081
  servlet:
    context-path: /tcom-admin-api

#logging:
#  config: classpath:log/logback-spring.xml


#logging:
#  level:
#    org.springframework: TRACE
#    io.swagger: TRACE
#    com.github.xiaoymin: TRACE


# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.zhu.tcomadminapi.controller

# knife4j???????????????
knife4j:
  enable: false
  setting:
    language: zh_cn
  basic:
    enable: true    #??????
    username: admin   #???
    password: 123456  #??

auth:
  ignore_urls:
    - /v1/login
    - /zhu/auth/captcha
    - /actuator/**
    - /v3/api-docs/**
    - /webjars/**
    - /swagger/**
    - /swagger-resources/**
    - /swagger-ui.html
    - /swagger-ui/**
    - /doc.html
    - /
    - /common/**
    - /v1/data/**



aliyun:
  oss:
    # oss?????????
    endpoint: oss-cn-nanjing.aliyuncs.com
    # ?????????????
    accessKeyId: LTAI5tEHc72qeWynxpJLHRfV
    # ????????????oss????????????
    accessKeySecret: L2sqJBb53oXSwqOOwwMST4WnrihkxY
    # oss?????
    bucketName: dbz0423

